### PR TITLE
Set jupyter server shutdown timeout to 10 minutes

### PR DESCRIPTION
**Pull request by lucyzhang929**

### CODE REVIEW

**Comment by barbaravaldez** [comment]
why do you need to add this timeout?

**Review by barbaravaldez — APPROVED** [review]

**Comment by lucyzhang929** [comment]
@barbaravaldez The last notebook smoke test was failing because the jupyter server shutdown before the notebook kernel could load. I'm increasing the timeout to 10 (from default value of 5) to fix the smoke test.

**Comment by Charles-Gagnon** [comment]
Another reason to have 0 be "never shutdown" - what's stopping something from happening such that 10min timeout isn't enough? Granted, that probably means something else is going wrong but it'd still be good to not have it fail because of the server shutting down since that's not something we're specifically wanting to test in these tests.

Although adding a test to verify the server shutting down is not a bad idea now that I think about it...

**Comment by lucyzhang929** [comment]
Updated the timeout to 0 (no timeout). @Charles-Gagnon tests for jupyter server shutting down correctly is a good idea. I'll look at that next Monday.

**Review by Charles-Gagnon — APPROVED** [review]

**Pull request merged**
